
services:
  api:
    build:
      context: .
      dockerfile: ChatBot.Api/Dockerfile
    ports:
      - "5000:80"

  ui:
    build:
      context: ./ChatBot.UI
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api